### ISSUE TITLE
Could you please fix the code?

### ISSUE THREAD

**Issue by lishiyuwhu** [nvlong21/Lightweight-face-detection-CenterNet#7]
There are some merge conflict in your code.

https://github.com/nvlong21/Lightweight-face-detection-CenterNet/blob/185db58f63cd123608a0bf5f7024a8c15261e018/centerface.py#L8

And the pre_process() in centerface.py is nener used, I think get_affine_transform() is neccessary.

**Comment by nvlong21** [comment]
Thanks for your contribution!
